#ifndef LV_CONF_H
#define LV_CONF_H
#define LV_COLOR_FORMAT_DEFAULT LV_COLOR_FORMAT_ARGB8888
#define LV_USE_STDLIB_MALLOC LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB
#define LV_USE_OS LV_OS_NONE
#define LV_FONT_MONTSERRAT_14 0
#define LV_FONT_MONTSERRAT_14_ALIGNED 0
#define LV_USE_CUSTOM_FONT_DEFAULT 1
#define LV_FONT_CUSTOM_DECLARE extern const lv_font_t dialysis_font;
#define LV_FONT_DEFAULT (&dialysis_font)
#define LV_USE_FONT_COMPRESSED 0
#define LV_USE_THORVG 0
#define LV_USE_THORVG_INTERNAL 0
#define LV_USE_SDL 0
#define LV_USE_LOG 0
#define LV_BUILD_EXAMPLES 0
#define LV_USE_FREETYPE 0
#define LV_USE_TINY_TTF 0
#define LV_USE_LODEPNG 0
#define LV_USE_LIBPNG 0
#define LV_USE_BMP 0
#define LV_USE_TJPGD 0
#define LV_USE_LIBJPEG_TURBO 0
#define LV_USE_GIF 0
#define LV_USE_FFMPEG 0
#define LV_USE_RLOTTIE 0
#define LV_USE_SVG 0
#define LV_USE_LZ4 0
#define LV_USE_FS_STDIO 0
#define LV_USE_FS_POSIX 0
#define LV_USE_FS_MEMFS 0
#define LV_USE_FONT_MANAGER 0
#endif
