# Reviewed linux-software-ui-1 profile; no implicit third-party downloads.
set(DIALYSISLAB_GUI_DEPS "${CMAKE_SOURCE_DIR}/build/gui-deps" CACHE PATH "Verified pinned source cache")
execute_process(COMMAND ${Python3_EXECUTABLE} ${CMAKE_SOURCE_DIR}/tools/fetch_gui.py
    --cache ${DIALYSISLAB_GUI_DEPS} --offline RESULT_VARIABLE gui_integrity)
if(NOT gui_integrity EQUAL 0)
    message(FATAL_ERROR "Fetch/verify GUI sources first with tools/fetch_gui.py")
endif()
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON CACHE BOOL "" FORCE)
foreach(feature TEST TESTS AUDIO JOYSTICK HAPTIC HIDAPI SENSOR DBUS IBUS WAYLAND OPENGL OPENGLES VULKAN KMSDRM LIBUDEV)
    set(SDL_${feature} OFF CACHE BOOL "" FORCE)
endforeach()
foreach(feature XCURSOR XINPUT XFIXES XRANDR XSCRNSAVER XSHAPE XDBE)
    set(SDL_X11_${feature} OFF CACHE BOOL "" FORCE)
endforeach()
set(HAVE_LINUX_INPUT_H OFF CACHE BOOL "No raw evdev" FORCE)
set(HAVE_INPUT_KD OFF CACHE BOOL "No console keyboard" FORCE)
# Optional local platform-header prefix avoids installing host-wide packages.
set(DIALYSISLAB_XEXT_PREFIX "" CACHE PATH "Existing/extracted platform Xext development prefix")
if(DIALYSISLAB_XEXT_PREFIX)
    set(HAVE_XEXT_H "${DIALYSISLAB_XEXT_PREFIX}/include/X11/extensions/Xext.h" CACHE STRING "" FORCE)
    include_directories("${DIALYSISLAB_XEXT_PREFIX}/include")
endif()
add_subdirectory("${DIALYSISLAB_GUI_DEPS}/SDL2-2.32.10" gui-sdl EXCLUDE_FROM_ALL)
get_target_property(selected_sdl SDL2-static SOURCES)
list(FILTER selected_sdl EXCLUDE REGEX "/src/libm/")
set_property(TARGET SDL2-static PROPERTY SOURCES "${selected_sdl}")
foreach(feature STRTOK_R ACOS ASIN ATAN ATAN2 CEIL COS EXP FABS FLOOR FMOD LOG LOG10 POW SIN SQRT TAN)
    if(NOT HAVE_${feature})
        message(FATAL_ERROR "Selected SDL profile requires libc ${feature}; fallback license not adopted")
    endif()
endforeach()
file(WRITE "${CMAKE_BINARY_DIR}/gui-selected-sdl-sources.txt" "${selected_sdl}")
set(LV_BUILD_CONF_PATH "${CMAKE_SOURCE_DIR}/src/ui/lv_conf.h" CACHE PATH "" FORCE)
foreach(feature CONFIG_LV_BUILD_EXAMPLES CONFIG_LV_BUILD_DEMOS CONFIG_LV_USE_THORVG CONFIG_LV_USE_THORVG_INTERNAL LV_USE_FIND_PACKAGE LV_USE_PKG_CONFIG LV_USE_FETCH_DEPENDENCIES LV_BUILD_INSTALL)
    set(${feature} OFF CACHE BOOL "" FORCE)
endforeach()
add_subdirectory("${DIALYSISLAB_GUI_DEPS}/lvgl-9.6.0" gui-lvgl EXCLUDE_FROM_ALL)
find_package(Threads REQUIRED)
add_executable(device-ui src/ui/device_ui.cpp src/ui/font.cpp)
target_include_directories(device-ui PRIVATE src "${DIALYSISLAB_GUI_DEPS}/lvgl-9.6.0/include")
target_link_libraries(device-ui PRIVATE lvgl SDL2-static Threads::Threads)
target_compile_options(device-ui PRIVATE -Wall -Wextra -Wpedantic -Werror -fno-fast-math
    "-ffile-prefix-map=${CMAKE_SOURCE_DIR}=." "-ffile-prefix-map=${CMAKE_BINARY_DIR}=build")
if(DIALYSISLAB_SANITIZE)
    foreach(gui_target device-ui lvgl SDL2-static)
        target_compile_options(${gui_target} PRIVATE -fsanitize=address,undefined -fno-sanitize-recover=all -fno-omit-frame-pointer)
    endforeach()
    target_link_options(device-ui PRIVATE -fsanitize=address,undefined)
endif()
